name: .NET

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output release
    - name: Documentation
      run: mkdir release/docs && dotnet fsdocs build --clean --output release/docs --properties Configuration=Release Version=${VERSION} --parameters root https://avalente.github.io/ --strict
    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: release/Fable.Modulo.${{env.VERSION}}.nupkg
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: release/docs/
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: avalente/avalente.github.io
        publish_dir: ./release/docs/
